### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by IlyaMokin** [Gaziz666/Web.whatsapp.page#1]
Thanks, good work! It needs a few small enhancements only
![image](https://user-images.githubusercontent.com/5592397/88586931-d7d7c700-d05d-11ea-8cb9-c0dd64523d73.png)

**Comment by Gaziz666** [comment]
hi thank you for your evaluation.
I have corrected mistakes

**Comment by Gaziz666** [comment]
> Thanks, good work! It needs a few small enhancements only
> ![image](https://user-images.githubusercontent.com/5592397/88586931-d7d7c700-d05d-11ea-8cb9-c0dd64523d73.png)
hi thank you for your evaluation.
I have corrected mistakes

**Comment by Gaziz666** [comment]
hi thank you for your evaluation.
I have corrected mistakes

**Comment by ilya4321** [comment]
Looking good now. We will checking your js tasks soon. Thanks for the efforts and patience!
